FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_LIBNGHTTP2 QUIET libnghttp2)
SET(LIBNGHTTP2_DEFINITIONS ${PC_LIBNGHTTP2_CFLAGS_OTHER})

FIND_PATH(LIBNGHTTP2_INCLUDE_DIR nghttp2/nghttp2.h
          HINTS ${PC_LIBNGHTTP2_INCLUDEDIR} ${PC_LIBNGHTTP2_INCLUDE_DIRS}
          PATH_SUFFIXES libnghttp2)

FIND_LIBRARY(LIBNGHTTP2_LIBRARY NAMES nghttp2
             HINTS ${PC_LIBNGHTTP2_LIBDIR} ${PC_LIBNGHTTP2_LIBRARY_DIRS})

INCLUDE(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set LIBNGHTTP2_FOUND to TRUE
# if all listed variables are TRUE
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibNghttp2 DEFAULT_MSG
                                  LIBNGHTTP2_LIBRARY LIBNGHTTP2_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBNGHTTP2_INCLUDE_DIR LIBNGHTTP2_LIBRARY)

SET(LIBNGHTTP2_LIBRARIES ${LIBNGHTTP2_LIBRARY})
SET(LIBNGHTTP2_INCLUDE_DIRS ${LIBNGHTTP2_INCLUDE_DIR})
